name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel
    - run: dotnet build "TodoApi.csproj"
    - run: dotnet publish --configuration Release "TodoApi.csproj" 
    - name: Build docker image
      run: |
        docker build -f ${{ github.workspace }}/Dockerfile -t dotnet-core-api:${{ github.sha }} .
    - name: Build and Publish Tag Docker image
      uses: VaultVulp/gp-docker-action@1.1.7
      with:
          image: dotnet-core-api:${{ github.sha }}
          registry: docker.pkg.github.com
          githubOrg: override-org # optional
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }} 
